# config/packages/vich_uploader.yaml

vich_uploader:
  db_driver: orm  # or mongodb or propel or phpcr, depending on your DB

  mappings:
    room_image:  # This is the mapping name you'll refer to in your Room entity
      uri_prefix: '%rooms_directory%'
      # The base path for your uploaded files as accessed from the web
      upload_destination: '%kernel.project_dir%/public/uploads/rooms'  # Where files should be uploaded on your server
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  # Optionally, specify a namer service
